## Machine Learning - Lab 01
* Full name: Đinh Anh Huy
* Student ID: 18110103

In [1]:
# Import library
import numpy as np 
import matplotlib.pyplot as plt 
import random
import pandas as pd
from sklearn import datasets

### 1. Hãy dùng bộ dữ liệu dibetes để thiết lập mô hình Linear Regresion.

In [2]:
# Read data
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)
print(">> Shape of diabetes data except label: ", diabetes_X.shape)

# Split data: 2 for testing and the other for training
diabetes_X_train, diabetes_y_train = diabetes_X[:-2], diabetes_y[:-2].reshape(1,-1).T
diabetes_X_test, diabetes_y_test = diabetes_X[-2:], diabetes_y[-2:].reshape(1,-1).T
print(">> Shape of training data: {} and testing data: {}  ".format(diabetes_X_train.shape, diabetes_X_test.shape))

>> Shape of diabetes data except label:  (442, 10)
>> Shape of training data: (440, 10) and testing data: (2, 10)  


In [3]:
def linear_regression_model(X_train, y_train, X_test, y_test):
    # Add 1 into X_train
    one_train = np.ones((X_train.shape[0], 1))
    Xbar = np.concatenate((one_train, X_train), axis = 1)

    # Calculate W
    A = np.dot(Xbar.T, Xbar)
    b = np.dot(Xbar.T, y_train)
    W = np.dot(np.linalg.pinv(A), b)
    
    # Add 1 into X_test
    one_test = np.ones((X_test.shape[0], 1))
    Xbar = np.concatenate((one_test, X_test), axis = 1)
    
    # Calculate y_predict
    y_predict = np.dot(Xbar, W)
    
    return W, y_predict

In [4]:
W, y_predict = linear_regression_model(diabetes_X_train, diabetes_y_train, diabetes_X_test, diabetes_y_test)
print("W = \n", W)
print(">> Shape of W: ", W.shape)

W = 
 [[ 152.10620412]
 [  -9.38654069]
 [-239.50541995]
 [ 519.71747928]
 [ 324.62241148]
 [-788.75647584]
 [ 474.10341796]
 [  98.46801188]
 [ 175.8004285 ]
 [ 749.38200399]
 [  67.88567794]]
>> Shape of W:  (11, 1)


### 2. Hãy tìm target values của *diabetes_X_test* rồi so sánh với target values trong *diabetes_y_test*.

In [5]:
MSE = np.square(np.subtract(diabetes_y_test, y_predict)).mean()

print("\n>> Predicted target values on testing set: \n", y_predict)
print("\n>> Target values on testing set: \n", diabetes_y_test)
print("\n>> Mean squared error of model: ", MSE)


>> Predicted target values on testing set: 
 [[211.74929866]
 [ 53.19292183]]

>> Target values on testing set: 
 [[220.]
 [ 57.]]

>> Mean squared error of model:  41.283958422940856


### 3. Tìm hiểu sklearn và làm lại yêu cầu câu 2.

In [6]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(diabetes_X_train, diabetes_y_train)

print(">> Matrix W except bias: \n", lr.coef_)
print("\n>> Bias: ", lr.intercept_)

>> Matrix W except bias: 
 [[  -9.38654069 -239.50541995  519.71747928  324.62241148 -788.75647584
   474.10341796   98.46801188  175.8004285   749.38200399   67.88567794]]

>> Bias:  [152.10620412]


In [7]:
y_pred = lr.predict(diabetes_X_test)
print(">> Predicted target values on testing set: \n", y_pred)

from sklearn.metrics import mean_squared_error

# Calculation of Mean Squared Error (MSE)
MSE = mean_squared_error(diabetes_y_test, y_pred)
print("\n>> Mean squared error of model: ", MSE)

>> Predicted target values on testing set: 
 [[211.74929866]
 [ 53.19292183]]

>> Mean squared error of model:  41.283958422945254
