In [4]:
import numpy as np 
import pandas as pd
import math
from scipy.spatial.distance import cdist # Tính khoảng cách giữa các cặp điểm trong 2 tập hợp một cách hiệu quả
import random
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline
rnd = np.random.RandomState(3)

In [5]:
np.random.seed(18) # Cố định dữ liệu random sau mỗi lần chạy là giống nhau
# Danh sách các tâm cụm đồng thời là kỳ vọng để tạo mẫu
means = [[2, 2], [8, 3], [3, 6]]
# Ma trận hiệp phương sai cấp 2
cov = [[1, 0], [0, 1]]
# Số lượng điểm mẫu cho mỗi cụm
N = 200
# Tạo mẫu ngẫu nhiên 500 điểm cho mỗi cụm theo phân phối chuẩn có kỳ vọng (means) và ma trận hiệp phương sai (cov)
X0 = np.random.multivariate_normal(means[0], cov, N)
X1 = np.random.multivariate_normal(means[1], cov, N)
X2 = np.random.multivariate_normal(means[2], cov, N)
# Nối X0, X1, X2 thành một bộ dữ liệu lớn
X_np = np.concatenate((X0, X1, X2), axis = 0)
K = 3 # 3 cụm
# Tạo vector cột làm nhãn cho dữ liệu ở trên
y_np = np.asarray([0]*N + [1]*N + [2]*N).T

In [10]:
dist = cdist(X_np, X_np)
print(dist)
print(dist.shape)
# print(np.argmin(dist))
print(dist[1,0])
# print(np.arange(X_np.shape[0]))

[[0.         2.04096839 1.60837219 ... 1.47832342 3.6075551  1.81208583]
 [2.04096839 0.         0.74017703 ... 3.37923776 5.49683515 3.83622532]
 [1.60837219 0.74017703 0.         ... 2.77544696 4.85224941 3.30575491]
 ...
 [1.47832342 3.37923776 2.77544696 ... 0.         2.13930635 0.71160911]
 [3.6075551  5.49683515 4.85224941 ... 2.13930635 0.         1.94793324]
 [1.81208583 3.83622532 3.30575491 ... 0.71160911 1.94793324 0.        ]]
(600, 600)
2.040968392070233


In [11]:
def get_min_distance(dist):
    min_val = dist[1,0]
    row_index = 1
    col_index = 0
    for i in range(2, dist.shape[0]):
        for j in range(i):
            if dist[i,j] < min_val:
                min_val = dist[i,j]
                row_index = i
                col_index = j
    return min_val, (row_index, col_index)

In [ ]:
def single_linkage()

In [ ]:
def hierarchical_clustering(data, linkage, no_of_cluster):
    # tính ma trận khoảng cách của tất cả các mẫu trong data
    dist = cdist(data, data)
    # gán mỗi điểm dữ liệu như một cụm đơn
    labels = [np.arange(data.shape[0])]
    
    
    
        

In [17]:
d = {}
d[0] = [(10, 5)]
d[1] = (11,2)
print(2 not in d)

True
